title: Enzyme Conference
locale: en_US
lang: en
url: https://enzyme.mit.edu/conference

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag