title: Enzyme Conference
tagline: Enzyme Conference 2023 | February 22-24, 2023 University of Colorado Boulder, CO, USA
description: This workshop aims at bringing together the contributors and users of Enzyme in particular, and people interested in automatic differentiation within the LLVM infrastructure in general, for two days of fast-paced high-bandwidth idea exchange and collaboration bootstrapping.
logo: /img/logo.png
locale: en_US
lang: en
url: https://enzyme.mit.edu/conference
baseurl: /conference


exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag