FROM mcr.microsoft.com/devcontainers/javascript-node:1-20-bookworm

RUN sudo apt-get update && sudo apt-get install -y libjpeg-dev webp libpng-dev libavifile-0.7c2 libopenjpip7 imagemagick libvips-tools